name: Build Android Release

on:
  push:
    branches: [ "main" ] # 当 main 分支有 push 时触发
  workflow_dispatch: # 允许手动触发 workflow

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
      - name: 创建 secrets.json 文件
        run: |
          echo "${{ secrets.SECRETS_JSON_CONTENT }} | base64 -d" > secrets.json
      - name: 获取 Flutter 依赖
        run: flutter pub get
      - name: 构建 APK
        run: flutter build apk --dart-define-from-file=secrets.json
      - name: 上传 APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
